apiVersion: v1
kind: Service
metadata:
  name: api-inferencia-service
spec:
  selector:
    app: api-inferencia
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: stream
      port: 8503
      targetPort: 8503
